dearborn-coding-club/website-base-backend

server/server/settings.py
server/server/urls.py
server/server/views.py
server/templates/base.html
server/templates/index.html

If one visits localhost:8000, the message "Welcome to Dearborn Coding Club" now displays. Probably a good idea to thik about the design of the website in something like Figma or Adobe XD, etc.

feat: Welcome to Dearborn Coding Club nows displays

---

README.md
README.old.md
server/server/settings.py

@jimwallace335 discovered that our local development docs were out of date when he tried to run everything on his machine. This PR updates them and adds the correct URI's to the `settings.py` file so local development is successful.

Correct local development docs

---

.github/workflows/fly.yml

Trying to add fly.yml Github Action. However, even if this gets merged in, we still need a fly.io api secret for the action to actually work. 
https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
Attempts to resolve #19

Added fly.yml config

---

server/static/style.css
server/templates/base.html

- Adds base CSS class to website to set up for eventual styling and React work.

Add base css file

---

server/static/style.css
server/templates/base.html

- Center the logo and title text.

Center everything

---

server/static/app.js
server/templates/base.html

Closes https://github.com/dearborn-coding-club/website-base-backend/issues/41
- Adds initial JS file that outputs "Hello world" to the console on startup.

Add initial js file

---

server/templates/base.html

- Removes accidentally included quote from base template.

Remove accidentally included quote

---

Dockerfile

- Added -y to upgrade command in docker file to run on both windows and mac.

Add -y to upgrade command in docker file

---

project/urls.py
project/views.py
templates/react/staging.html

- Adds missing staging route to Django project
- Updates `project/views.py` to include a new `staging_view` function
- Adds `staging.html` template to the project.

Add staging route for Django

---

README.md

- Adds readme instructions for accessing staging

Add Readme instructions for accessing staging

---

.github/workflows/PULL_REQUEST_TEMPLATE/pull_request_template.md

- Adds base pull request template to the repository (see https://github.com/dearborn-coding-club/website-base-backend/issues/43).

Add base pull request template

---

CONTRIBUTING.md

- Adds `CONTRIBUTING.md` that includes the guidelines for contributing to the project.
- Generated using https://generator.contributing.md/

Adds `CONTRIBUTING.md` file

---

CODE_OF_CONDUCT.md

- Adds `CODE_OF_CONDUCT.md` that includes the guidelines for contributing to the project.
- Generated using https://generator.contributing.md/

Add `CODE_OF_CONDUCT.md` file

---

Makefile
README.md

- Fixes `README.md` doc to have accurate run instructions.
- Fixes `make run` file to remove front end steps.

Fix `README.md` docs and fix `make run` alias

---

project/urls.py
project/views.py

- Adds a scaffolded JSON response for the `/notes` endpoint.

Add scaffolded json response

---

README.md

- Updates docs to include mermaid architecture diagram.
[Click here](https://github.com/dearborn-coding-club/website-base-backend/pull/88/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) to view the file as Markdown.

Update `README.md` to include system design diagram

---

README.md
requirements.txt

- Adds a deploy status badge to readme file.
- Fixes some minor typos in readme.

docs: Add deploy status badge to `README.md`

---

.github/pull_request_template.md

- Improves PR template to have a `closes <issue` and `Background` section.
N/A

chore: Improve PR template

---

README.md

Updates the file structure diagram in the main `README.md` file for accuracy because we have improved our understanding since it was last updated.
- Updates `README.md` with file structure details

docs: Update filestructure documentation for understandability

---

accounts/serializers.py
accounts/urls.py
accounts/views.py
public_api/urls.py
public_api/views.py

References https://github.com/dearborn-coding-club/website-base-frontend/issues/88
We've needed an endpoint to provide a list of user data so we can populate the community page. This PR introduces a `/profile` endpoint that returns a list of user profiles with their LeetCode statistics. This PR also introduces a `/user` endpoint that returns a list of users with their profile information and auth details.
- Introduces a `/profile` endpoint.
- You can either hit `/profile` and retrieve a list of user _profiles_, not including their auth information or hit `/profile/<id>` to retrieve a specific user profile.
- Introduces a `/user` endpoint.
- You can can either hit `/user` and retrieve a list of _users_, which includes information about the users profile and their auth information. You can …

feat: Introduce `/profile` and `/user` endpoint

---

.github/pull_request_template.md

Closes https://github.com/dearborn-coding-club/website-base-backend/issues/122
Our pull request template for this repo differs from the examples in other repos. I like they way we configured it in https://github.com/dearborn-coding-club/website-base-frontend, so I'm bringing over that template here.
- Reorders the pull request template for better formatting.
- Removes the `Screenshots` section from the template as the backend often doesn't have any visual representation of the changes.

docs: Improve pull request template

---

README.md

References https://github.com/dearborn-coding-club/website-base-backend/issues/115
- Updates `README.md` in various places for accuracy.
Our `README.md` has been in a state of inaccuracy for a while now - we've updated how we run the backend app but haven't made the corresponding updates to the documentation. This PR does a sweep through the current doc and updates it to reflect the current state of the app.

docs: Improve readme for accuracy

---

.env.example
README.md
public_api/settings.py

Closes #138
- Fixes typos in settings.py
- Adds new .env.example
- Updates readme to help starting new application.
- Trying to help get volunteers up and running with README.md

Update to add a .env.example #138

---

public_api/settings.py

- Updates the host environment variable to remove a typo.

fix: Update postgres host variables
